### ISSUE TITLE
Logon Fail 

### ISSUE THREAD

**Issue by nisargshh** [Ar1i/Report-Bot-Web#15]
Im Getting a logon fail. http://prntscr.com/ew544z

**Comment by daniel11609** [comment]
The sentry doesn't work #10 or so

**Comment by nisargshh** [comment]
I tried that script, still didnt work.

**Comment by daniel11609** [comment]
Works for me tho

**Comment by ghost** [comment]
The Sentry script that comes with the bot doesn't have an issue with logon, it was creating a proper sentry file that the script could read & use that was broken, fixed by https://github.com/Ar1i/Report-Bot-Web/issues/10. If it is failing to login, you have the login details wrong.

**Comment by nisargshh** [comment]
I made sure they were not wrong.

**Comment by daniel11609** [comment]
Working for me though with 9/10 accounts. Maybe you are blocked for too many tries or something... No way that you disable steam guard? 

Am 30. April 2017 00:23:43 MESZ schrieb 5oClutch <notifications@github.com>:
