### ISSUE TITLE
Login failed!63 -  steam guard email

### ISSUE THREAD

**Issue by daniel11609** [Ar1i/Report-Bot-Web#16]
Keep getting this error eventhough i created sentry file for the account...
If i disable steam guard email everything works fine.

Is there away to get steam guard email to work. What about 2fa Accounts?

~/Report-Bot-Web-master/server$ node bot-report-web.js 76
Reporting SteamID: 76
Starting Accounts...

[STEAM CLIENT (ahme**) - Login failed!63

**Comment by ghost** [comment]
The steam sentry script that comes with the bot doesn't work. Another user made an issue report about this and posted his solution in the same thread. Just replace the entire steam sentry script with the one in this thread and it works fine: https://github.com/Ar1i/Report-Bot-Web/issues/10

**Comment by daniel11609** [comment]
Hey I appreciate your reply. Do you know if I will be able to use email guard and or 2fa steam app accounts. With the vapor report I can use both types of accounts. Thx a lot I will check it out. 

Am 19. April 2017 01:06:36 MESZ schrieb Derple343 <notifications@github.com>:

**Comment by ghost** [comment]
@daniel11609 I don't believe this script has 2FA code in it, but i haven't looked either since all my accounts are dedicated bots and I don't use them for gameplay.

**Comment by daniel11609** [comment]
Yea that's the problem... If I have a sentry file with 2fa.... Not sure but for example the steamhourboostv2 and the vapor report by luk1337 work fine with it. It's just 2 accounts with 2fa so I should be able to get 6 accounts with email. Thx a lot ;) 

Am 19. April 2017 01:17:04 MESZ schrieb Derple343 <notifications@github.com>:

**Comment by ghost** [comment]
Yeah, This doesn't have 2FA, although I just looked at Vapor's code and it has some kind of 'Vapor' API that I have no clue about.

In the meantime, if @sstokic-tgm could push his steam sentry script to the main repo, or if @Ar1i could do it, that would be awesome.

**Comment by daniel11609** [comment]
Hmm yea good luck with getting it into the main repo. 
I guess it's fine, because 6 Accounts are enough those 2 additional ones aren't that game breaking ;) 

Thx a lot 

Am 19. April 2017 01:25:59 MESZ schrieb Derple343 <notifications@github.com>:
