### ISSUE TITLE
Bots report only 1 time

### ISSUE THREAD

**Issue by RedizEric** [Ar1i/Report-Bot-Web#28]
Hello, i want to know why the 11 bots only report 1 time

`Reporting SteamID: ID Removed for privacy`
`Starting Accounts...`
`[GC - 0] Client Hello sent!`
`[GC - 9] Client Hello sent!`
`[GC - 10] Client Hello sent!`
`[GC - 3] Client Hello sent!`
`[GC - 5] Client Hello sent!`
`[GC - 8] Client Hello sent!`
`[GC - 7] Client Hello sent!`
`[GC - 2] Client Hello sent!`
`[GC - 1] Client Hello sent!`
`[GC - 6] Client Hello sent!`
`[GC - 4] Client Hello sent!`
`[GC - 10] Client Welcome received!`
`[GC - 10] Report request sent!`
`[GC - 10] MM Client Hello sent!`
`[GC - 9] Client Welcome received!`
`[GC - 9] Report request sent!`
`[GC - 9] MM Client Hello sent!`
`[GC - 0] Client Welcome received!`
`[GC - 0] Report request sent!`
`[GC - 0] MM Client Hello sent!`
`[GC - 0] MM Client Hello sent!`
`[GC - 10] MM Client Hello sent!`
`[GC - 9] MM Client Hello sent!`
`[GC - 3] Client Welcome received!`
`[GC - 3] Report request sent!`
`[GC - 3] MM Client Hello sent!`
`[GC - 3] MM Client Hello sent!`
`[GC - 7] Client Welcome received!`
`[GC - 7] Report request sent!`
`[GC - 7] MM Client Hello sent!`
`[GC - 7] MM Client Hello sent!`
`[GC - 8] Client Welcome received!`
`[GC - 8] Report request sent!`
`[GC - 8] MM Client Hello sent!`
`[GC - 8] MM Client Hello sent!`
`[GC - 1] Client Welcome received!`
`[GC - 1] Report request sent!`
`[GC - 1] MM Client Hello sent!`
`[GC - 1] MM Client Hello sent!`
`[GC - 5] Client Welcome received!`
`[GC - 5] Report request sent!`
`[GC - 5] MM Client Hello sent!`
`[GC - 5] MM Client Hello sent!`
`[GC - 2] Client Welcome received!`
`[GC - 2] Report request sent!`
`[GC - 2] MM Client Hello sent!`
`[GC - 2] MM Client Hello sent!`
`[GC - 6] Client Welcome received!`
`[GC - 6] Report request sent!`
`[GC - 6] MM Client Hello sent!`
`[GC - 6] MM Client Hello sent!`
`[GC - 4] Client Welcome received!`
`[GC - 4] Report request sent!`
`[GC - 4] MM Client Hello sent!`
`[GC - 4] MM Client Hello sent!`
`[GC - (1)] Report with confirmation ID: 3242192898896167054 sent!`
`[GC - (2)] Report with confirmation ID: 3242192898896167055 sent!`
`[GC - (3)] Report with confirmation ID: 3242192898896167063 sent!`
`[GC - (4)] Report with confirmation ID: 3242192901043650674 sent!`
`[GC - (5)] Report with confirmation ID: 3242192901043650677 sent!`
`[GC - (6)] Report with confirmation ID: 3242192901043650703 sent!`
`[GC - (7)] Report with confirmation ID: 3242192901043650724 sent!`
`[GC - (8)] Report with confirmation ID: 3242192903191134219 sent!`
`[GC - (9)] Report with confirmation ID: 3242192903191134228 sent!`
`[GC - (10)] Report with confirmation ID: 3242192903191134254 sent!`
`[GC - (11)] Report with confirmation ID: 3242192903191134259 sent!`

`11 Reports for this faggot.\nThanks for using this Service! Credits for the Script to askwrite & TROLOLO.`
`Thanks for using this Service!`
`MafiaBot`

Second report 1 hour later

`Reporting SteamID: ID Removed for privacy`
`Starting Accounts...`

can you help me?

**Comment by Ar1i** [comment]
you need more accounts you can only report every 12 hours
