### ISSUE TITLE
OW CHECK

### ISSUE THREAD

**Issue by ghost** [Ar1i/Report-Bot-Web#3]
Wie mach ich mir nen Crontab der jede 5 Minuten nach einen OW checkt?
Benutze Debian

**Comment by Ar1i** [comment]
http://www.linuxquestions.org/questions/linux-general-1/how-to-set-cron-job-to-run-every-5-mins-61667/

**Comment by ghost** [comment]
Es geht nicht

**Comment by Ar1i** [comment]
Es geht wenn du es richtig machst ^^

**Comment by Alexey2532** [comment]
Habe n cornjob drauf der das refresht, aber er aktualisiert "banned" nicht.

**Comment by Ar1i** [comment]
@Alexey2532 @yodabosten addet mich mal bitte auf Steam, http://steamcommunity.com/id/ar1ixyz/ um was zu schauen

**Comment by Ar1i** [comment]
benutzt die neuste ow-check.php dann geht alles
