### ISSUE TITLE
after click report nothing happend

### ISSUE THREAD

**Issue by dasyah** [Ar1i/Report-Bot-Web#33]
after click report, nothing happened just reload the page and report list empty where did I wrong? I already follow all instruction and already install nodejs on my VPS

**Comment by Marcofurio30** [comment]
> after click report, nothing happened just reload the page and report list empty where did I wrong? I already follow all instruction and already install nodejs on my VPS

Hi, i've the same problem, did you fix it?

**Comment by Ar1i** [comment]
If you're using apache2/nginx as webserver. The index file probably has no rights to write to the log folder or to create a file there. You need to set the rights correctly, then it will work.

chown/chmod is needed for that if you're on linux

**Comment by Marcofurio30** [comment]
> If you're using apache2/nginx as webserver. The index file probably has no rights to write to the log folder or to create a file there. You need to set the rights correctly, then it will work.
> 
> chown/chmod is needed for that if you're on linux

Hello, thanks alot for your reply, i've already put 777 to the index and the reportbot / log files

**Comment by Marcofurio30** [comment]
Ok, little update on this, i've change the owner from "root" to www-data for every folder.
I've also installed the php7.0-xml package as i saw an error on the error.log in apache folder.
So now, i get this (see screenshot)
![reportbot](https://user-images.githubusercontent.com/42481322/62377574-53825f00-b543-11e9-84c1-e172f7cc02e3.PNG)

**Comment by Ar1i** [comment]
Which error? It looks like it's working

**Comment by Marcofurio30** [comment]
Thanks for your reply, it don't write "Report with confirmation ID: xxxxxxxxxxxxxxxxxxxxxx sent!"

**Comment by Ar1i** [comment]
Thats probably cause the accounts are on cooldown. Don't know if it's still like that, it was 1 report every 12 hours orso. Then you need to use other accounts. There is no function like that in this script, so not everyone can sell reports. But it's pretty easy to add.

**Comment by Marcofurio30** [comment]
Its already new account, i'm going to try with other new accounts to see if its working.
And i don't want to sell reports, just want this report bot for me and my friends
Thanks again for your reply, i'll let you know if it works !!

**Comment by Marcofurio30** [comment]
I've just crated these accounts and this is what i get when i report


[STEAM CLIENT - 2] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 6] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 5] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 8] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 1] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 3] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 0] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 7] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 4] Account is probably ingame! Logged out!
Error: Disconnected
[STEAM CLIENT - 9] Account is probably ingame! Logged out!
Error: Disconnected

**Comment by dasyah** [comment]
after instalation, index web still blank,before that work on cpanel,now im  trying ispconfig webpanel and its just blank after isntalation,I dont know much about php maybe someone know this problem?:(

**Comment by Ar1i** [comment]
look at the error log file, maybe it can help you
