### ISSUE TITLE
Sentry script

### ISSUE THREAD

**Issue by JailSeed** [Ar1i/Report-Bot-Web#34]
Does this script work? I enter login and password, but nothing happens.

**Comment by Ar1i** [comment]
Yes it works

**Comment by JailSeed** [comment]
But why does it not work for me?

**Comment by Ar1i** [comment]
Is it a new account? And you installed the node packages?

**Comment by JailSeed** [comment]
No, they are old. I have 11 prime accounts and tried all of them. Yes, of course, I wrote npm install.
