### ISSUE TITLE
Node scripts

### ISSUE THREAD

**Issue by Webisoft** [Ar1i/Report-Bot-Web#6]
I'm not sure if they fixed something or protos need update or sth else which i dont know but even if i added few accounts more i cant get any1 into OW.

Tried 6h / 12h / 24h report and even if logs are fine where i have confirmed reports its like nothing. Any solution what i should do ? Or what should be fixed ?

Atm testing classic method with askwrite node script but nothing tbh, stopped after node script.js.

**Comment by Alexey2532** [comment]
How much accounts?

**Comment by Webisoft** [comment]
16

**Comment by Alexey2532** [comment]
can you wirte here what the console gives you as output?

**Comment by Webisoft** [comment]
Reporting SteamID: 76561198325944588
Starting Accounts...
[GC - 2] Client Hello sent!
[GC - 14] Client Hello sent!
[GC - 15] Client Hello sent!
[GC - 13] Client Hello sent!
[GC - 8] Client Hello sent!
[GC - 9] Client Hello sent!
[GC - 10] Client Hello sent!
[GC - 3] Client Hello sent!
[GC - 12] Client Hello sent!
[GC - 4] Client Hello sent!
[GC - 0] Client Hello sent!
[GC - 6] Client Hello sent!
[GC - 11] Client Hello sent!
[STEAM CLIENT - 3] Account is probably ingame! Logged out!
Error: Disconnected
[GC - 7] Client Hello sent!
[GC - 1] Client Hello sent!
[GC - 5] Client Hello sent!
[GC - 14] Client Welcome received!
[GC - 14] Report request sent!
[GC - 14] MM Client Hello sent!
[GC - 14] MM Client Hello sent!
[GC - 15] Client Welcome received!
[GC - 15] Report request sent!
[GC - 15] MM Client Hello sent!
[GC - 15] MM Client Hello sent!
[GC - 2] Client Welcome received!
[GC - 2] Report request sent!
[GC - 2] MM Client Hello sent!
[GC - 2] MM Client Hello sent!
[GC - 13] Client Welcome received!
[GC - 13] Report request sent!
[GC - 13] MM Client Hello sent!
[GC - 13] MM Client Hello sent!
[STEAM CLIENT - 1] Account is probably ingame! Logged out!
Error: Disconnected
[GC - 10] Client Welcome received!
[GC - 10] Report request sent!
[GC - 10] MM Client Hello sent!
[GC - 10] MM Client Hello sent!
[GC - 8] Client Welcome received!
[GC - 8] Report request sent!
[GC - 8] MM Client Hello sent!
[GC - 8] MM Client Hello sent!
[GC - 9] Client Welcome received!
[GC - 9] Report request sent!
[GC - 9] MM Client Hello sent!
[GC - 9] MM Client Hello sent!
[GC - 12] Client Welcome received!
[GC - 12] Report request sent!
[GC - 12] MM Client Hello sent!
[GC - 12] MM Client Hello sent!
[GC - 4] Client Welcome received!
[GC - 4] Report request sent!
[GC - 4] MM Client Hello sent!
[GC - 4] MM Client Hello sent!
[GC - 0] Client Welcome received!
[GC - 0] Report request sent!
[GC - 0] MM Client Hello sent!
[GC - 0] MM Client Hello sent!
[GC - 6] Client Welcome received!
[GC - 6] Report request sent!
[GC - 6] MM Client Hello sent!
[GC - 11] Client Welcome received!
[GC - 11] Report request sent!
[GC - 11] MM Client Hello sent!
[GC - 11] MM Client Hello sent!
[GC - 6] MM Client Hello sent!
[GC - 7] Client Welcome received!
[GC - 7] Report request sent!
[GC - 7] MM Client Hello sent!
[GC - 7] MM Client Hello sent!
[GC - 5] Client Welcome received!
[GC - 5] Report request sent!
[GC - 5] MM Client Hello sent!
[GC - 5] MM Client Hello sent!
[GC - (1)] Report with confirmation ID: 3186124821708669236 sent!
[GC - (2)] Report with confirmation ID: 3186124821708669247 sent!
[GC - (3)] Report with confirmation ID: 3186124821708669252 sent!
[GC - (4)] Report with confirmation ID: 3186124821708669254 sent!
[GC - (5)] Report with confirmation ID: 3186124823856152774 sent!
[GC - (6)] Report with confirmation ID: 3186124823856152777 sent!
[GC - (7)] Report with confirmation ID: 3186124823856152822 sent!
[GC - (8)] Report with confirmation ID: 3186124823856152829 sent!
[GC - (9)] Report with confirmation ID: 3186124823856152816 sent!
[GC - (10)] Report with confirmation ID: 3186124823856152855 sent!
[GC - (11)] Report with confirmation ID: 3186124823856152872 sent!
[GC - (12)] Report with confirmation ID: 3186124823856152928 sent!
[GC - (13)] Report with confirmation ID: 3186124826003636400 sent!
[GC - (14)] Report with confirmation ID: 3186124826003636463 sent!

**Comment by Alexey2532** [comment]
npm install steam
update mal steam

**Comment by Webisoft** [comment]
Will this help ? 

I mean, what will be changed after instaling npm steam ?  Already installed will test it today.

**Comment by Alexey2532** [comment]
I mean on your device you run this
ofc, if you don't have it on ur device i think this is the solution.

**Comment by Webisoft** [comment]
I'v installed steam, should i do sth additional ? or it will work just after install ?

**Comment by senekapa** [comment]
npm ERR! Error: No compatible version found: steam@'^1.4.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.3","0.1.0","0.1.1","0.2.0","0.3.0","0.3.1","0.4.0","0.4.1","0.4.2                ","0.4.3","0.4.4","0.4.5","0.4.6","0.4.7","0.4.8","0.4.9","0.5.0","0.5.1","0.5.2                ","0.5.3","0.5.4","0.5.5","0.5.6","0.5.7","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4                ","0.6.5","0.6.6","0.6.7","0.6.8","1.0.0","1.1.0","1.2.0","1.3.0","1.4.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.j                s:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry                -client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-642.4.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "steam"
npm ERR! cwd /var/report-bot
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/report-bot/npm-debug.log
npm ERR! not ok code 0

How can I solve this problem?

**Comment by Webisoft** [comment]
I have
node v7.3.0
npm 4.0.5
steam 1.4.0
and all works well, atm testing if ppl actually will get into OW.

I'm not any specialist but what OS do you use ? Maybe think about updating everything.

**Comment by Alexey2532** [comment]
@DuDuxd 
npm ERR! Error: No compatible version found: steam@'^1.4.0'
It even says you the problem. write in console "npm install steam" without ""
@Webisoft What os?

**Comment by Webisoft** [comment]
debian 7

**Comment by senekapa** [comment]
I tried with that version and still does not work

**Comment by senekapa** [comment]
How do I connect with VPS website and here you put $ steam_web_key = "";

**Comment by Webisoft** [comment]
Log in into you account by using this link: https://steamcommunity.com/login/home/?goto=%2Fdev%2Fapikey

Generate code, and c+p into file.

**Comment by senekapa** [comment]
What should I change here? package.json

**Comment by Webisoft** [comment]
why would you edit package.json lol ;o

**Comment by senekapa** [comment]
And then how to connect VPS my website?

**Comment by Webisoft** [comment]
@DuDuxd Your problems isnt issue about my problem which are fixed i think. read readme.txt radat writed everything u need to know how to setup this.
