### ISSUE TITLE
Stuck at Starting Accounts...

### ISSUE THREAD

**Issue by ghost** [Ar1i/Report-Bot-Web#9]
Moin,
habe ein Problem: der Bot hängt bei Starting Accounts...; es kommt keinerlei Rückmeldung.

Die Logdatei mit der SteamID wird erstellt, jedoch wird kein Inhalt hinterlegt, die Datei bleibt leer.

**Comment by Lines08** [comment]
habe das problem nun auch @Ar1i

**Comment by Ar1i** [comment]
Evtl alle Reports verballert oder gebannte accs genommen?
